Revert "[IT-2361] Update Seqera enterprise version (#474)"
This reverts commit a96160cccb985060a818f24ffb8481d6313e5da3.

Failed to deploy with error..
CannotPullImageManifestError: Error response from daemon: unknown: resource
not found: repo private/nf-tower-enterprise/backend, tag v25.2 not found